internetshop/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login, name='login'),

    path('logout/', authapp.logout, name='logout'),

    path('register/', authapp.register, name='register'),
]

internetshop/internetshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('admin/', admin.site.urls),
]

internetshop/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [

    path('', mainapp.index, name='index'),
]

internetshop/authapp/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


class KpkUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, login, email, password, **extra_fields):
        """
        Create and save a user with the given login, email, and password.
        """
        if not login:
            raise ValueError('The given login must be set')
        email = self.normalize_email(email)
        user = self.model(login=login, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, login, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(login, email, password, **extra_fields)

    def create_superuser(self, login, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(login, email, password, **extra_fields)


class KpkUser(AbstractUser):
    objects = KpkUserManager()

    username = None

    login = models.CharField(
        'login',
        max_length=150,
        unique=True,
        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
        validators=[AbstractUser.username_validator],
        error_messages={
            'unique': "A user with that login already exists.",
        },
    )
    d_birth = models.DateField(null=True)
    avatar = models.ImageField(upload_to='avatars',
                               blank=True)

    USERNAME_FIELD = 'login'

internetshop/mainapp/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField('Название категории', max_length=60)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField('Название', max_length=60)
    desc = models.TextField('Описание', blank=True)
    # photo = models.ImageField('Фото', upload_to='images/', blank=True)
    year = models.IntegerField('Год выпуска')
    price = models.DecimalField('Цена', max_digits=6, decimal_places=2)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

internetshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from authapp.models import KpkUser


class LoginForm(AuthenticationForm):
    class Meta:
        model = KpkUser
        fields = ('login', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''


class RegisterForm(UserCreationForm):
    class Meta:
        model = KpkUser
        fields = ( 'email', 'login', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, item in self.fields.items():
            item.widget.attrs['class'] = f'form-control {name}'
            item.help_text = ''

internetshop/authapp/views.py
import django.contrib.auth as auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import LoginForm, RegisterForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            auth.login(request, form.get_user())
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = LoginForm()

    context = {
        'page_title': 'авторизация',
        'form': form,
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('auth:login'))
    else:
        form = RegisterForm()

        context = {
            'page_title': 'регистрация',
            'form': form,
        }
        return render(request, 'authapp/register.html', context)

internetshop/mainapp/views.py
from django.shortcuts import render


def index(request):
    context = {
        'page_title': 'главная'
    }
    return render(request, 'mainapp/index.html', context)

internetshop/authapp/templates/authapp/login.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div class="m-5">
        <h3>Авторизация</h3>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Войти</button>
        </form>
    </div>
{% endblock %}

internetshop/authapp/templates/authapp/register.html
{% extends 'mainapp/base.html' %}

{% block content %}
    <div class="register-form">
        <div class="form-title">Регистрация</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"
                   class="btn btn-success form-control"
                   value="зарегистрироваться">
        </form>
    </div>
{% endblock %}

internetshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ title|capfirst }} Интернет-магазин</title>
</head>
<body>
<div class="main-menu">
    <ul>
        <li>
            <a href="{% url 'main:index' %}">Главная</a>
        </li>
        <li>
            <a href="#">Каталог товаров</a>
        </li>
        <li>
            <a href="#">Корзина</a>
        </li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'authapp:logout' %}">Выйти</a>
            {% else %}
                <a href="{% url 'authapp:login' %}">Войти</a>
            {% endif %}
        </li>
    </ul>
</div>
{% block content %}
{% endblock %}
</body>
</html>

internetshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<h1>Интернет-магазин</h1>
{% endblock %}